# Welcome to Jekyll!
#
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daniel DeLayo's site
email: ddelayo@cs.stonybrook.edu # email of site's author
url: "https://danieldelayo.github.io"
author: Daniel DeLayo # name of site's author
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)




# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

#TODO
google_analytics: "G-CVLR2C85RK"

exclude:
  - Gemfile
  - Gemfile.lock

keep_files:
  - resume.pdf

# Build settings
remote_theme: riggraz/no-style-please@v0.3.1
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
